<!-- makeCacheMatrix: This function creates a list containing the matrix and a cache for the inverse. It includes setters and getters for the matrix and the inverse. -->

<!-- Setters for the matrix update the matrix value and clear the inverse cache. -->
<!-- Getters for the matrix and inverse simply return their current values. -->
<!-- cacheSolve: This function checks if the inverse of the matrix is already in the cache. -->

<!-- If the inverse is in the cache, it returns the cached value. -->
<!-- If not, it calculates the inverse, stores it in the cache using the setter from makeCacheMatrix, and      then returns the inverse. -->
```{r}
## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function

makeVector <- function(x = numeric()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        get <- function() x
        setmean <- function(mean) m <<- mean
        getmean <- function() m
        list(set = set, get = get,
             setmean = setmean,
             getmean = getmean)
}

cachemean <- function(x, ...) {
        m <- x$getmean()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- mean(data, ...)
        x$setmean(m)
        m
}

v <- makeVector(c(1,2,3,4,5))
v
cachemean(v)
cachemean(v)
````
```{r}


````
