## This is a markdown file

##This shows how assign used for variable assignment
```{r}
x<- 5
x
y <- 1:10
y
print(x)
msg<-"Hello World"
print(msg)

```
```{r}
x <- c(1.7, "a")
x
y <- c(TRUE, 2, 3, FALSE)
y

  

```


```{r}
x <- list(1, "a", TRUE, 1 + 4i)
x
```
```{r}
m <- matrix(1:6,nrow = 2, ncol = 3)
m
y <- 1:10
y
```

```{r}
x<-c(1,NA,3,4) #Na is not defined
is.na(x)
```

```{r}
# request sample of dataframes
head(mtcars)
#what this syntax did was to request the first 6 rows of the mtcars dataset
# i want the simple data frame to assign to a variable
df <- mtcars
df
# i want to see the structure of the data frame
str(df)
# i want to see the summary of the data frame
summary(df)
# i want to see the first 6 rows of the data frame
head(df)
# i want to see the last 6 rows of the data frame
tail(df)
```

```{r}
# request the syntax for read the file
x <- read.csv("mtcars.csv")
x

```

```{r}
vec <- c(1,2,3,4,5,6,7,8,9,10)
dput(vec)
x <- 1:5
y <- rnorm(5)
dump(c("x", "y"), file="mydata.R")
source("mydata.R")
```

```{r}
x <- list(foo =1:4, bar = 0.6)
x[1]
x
x["bar"]




`````
```{r}
x <- list(2, "a", "b", TRUE)
x[[2]]
``````

```{r}
x <- c(4, TRUE)
#check class of x
class(x)
x
``````
```{r}
x <- 4
class(x)
````
```{r}
x <- c(1,2,3)
y <- c(4,5,6)
z <- 1
x+z

rbind(x,y)
````

```{r}
x <- list(2, "a", "b", TRUE)
z <- x[[2]]
class(z)
x
````
```{r}
x <- c(3, 5, 1, 10, 12, 6)
x[x<6] <- 0
x



`````
