<!-- Exercise 1: Basic if-else Practice -->
<!-- Write an R script that takes a numeric variable x. The script should: -->

<!-- Print "x is positive" if x is greater than 0. -->
<!-- Print "x is zero" if x is equal to 0. -->
<!-- Print "x is negative" if x is less than 0. -->
```{r}
x <- 5
if (x > 0) {
  print("x is positive")
} else if (x == 0) {
  print("x is zero")
} else {
  print("x is negative")
}




```

<!-- Exercise 2: Combined if-else and Arithmetic -->
<!-- Create a script that calculates the body mass index (BMI) based on input variables weight (in kilograms) and height (in meters). The script should print: -->

<!-- "Underweight" if BMI < 18.5 -->
<!-- "Normal weight" if BMI is 18.5 to <25 -->
<!-- "Overweight" if BMI is 25 to <30 -->
<!-- "Obesity" if BMI >= 30 -->
<!-- BMI is calculated as  -->
<!-- BMI -->
<!-- = -->
<!-- weight -->
<!-- height -->
<!-- 2 -->
<!-- BMI=  -->
<!-- height  -->
<!-- 2 -->

<!-- weight -->
<!-- ​ -->
<!--  . -->
```{r}
for ( i in 1:15) {
  if(i %% 3 == 0 && i %% 5 == 0){
    print("fizzbuzz")
  }else if(i %% 3 == 0){
    print("Fizz")
  } else if (i %% 5 == 0){
    print("buzz")
  }else(
    print(i)
  )
  
  
}



```

<!-- Exercise 3: Basic for Loop Practice -->
<!-- Write a script that creates a vector v containing numbers 1 to 10. Using a for loop, print each number in v multiplied by 2. -->

<!-- Exercise 4: for Loop with Conditional Logic -->
<!-- Create a script that iterates through a vector of any ten integers. For each integer, the script should: -->

<!-- Print "Fizz" if the integer is divisible by 3, -->
<!-- Print "Buzz" if it is divisible by 5, -->
<!-- Print "FizzBuzz" if it is divisible by both 3 and 5, -->
<!-- Otherwise, just print the integer itself. -->
<!-- Exercise 5: Nested for Loops -->
<!-- Write a script that uses nested for loops to print a 5x5 multiplication table. The output should be formatted as a table where each entry (i, j) is the product of i and j. -->